### ISSUE TITLE
Fail to install.

### ISSUE THREAD

**Issue by shubhamyedage** [GordonSo/scimschema#11]
![image](https://user-images.githubusercontent.com/18259468/72241726-99bd0d80-360d-11ea-915d-27deef0e3192.png)
Failing to install new version.

**Comment by GordonSo** [comment]
🤔  I see what the problem is... I wonder why it wasn't a problem previously as nothing was changed... I have updated another version 0.1.47 with the newer package including the license and readme.rst now

**Comment by shubhamyedage** [comment]
Successfully updated! Thanks.
