### ISSUE TITLE
The ability to provide custom core schema

### ISSUE THREAD

**Issue by GordonSo** [GordonSo/scimschema#13]
As user of scimschema, I would like to validate responses against more core schemas as per rfc 7644 guidelines. 

It has been reported that the following schemas as missing:
- integrate Error
- SystemProviderConfig
- ResourceType
- Schema 

Idea;
To allow users to integrate their own core schemas.

Ref:
As per rfc 7644 guidelines (3.7.3 and 3.12 please refer to the diagram), the response is specified like this. So I guess either there should be provision for adding core schemas or provide basic error schema.

Another possible useful resource:
https://github.com/bjmc/scim-jsonschema/tree/master/rfc7643

![image](https://user-images.githubusercontent.com/4214928/73887421-63b52700-4863-11ea-8677-a5240318b8b2.png)

cc - reporter: @shubhamyedage

**Comment by GordonSo** [comment]
So I have studied up about part of the problem on rfc 7644, the missing core schema is by rfc standards so it should be included in the package instead of being defined by the user. 

https://github.com/GordonSo/scimschema/pull/15 now contains the meta-schema for written in the rfc:

1. SystemProviderConfig
2. ResourceType
3. Schema

It was just a matter of adding them into the core folder. I would suggest that you can make a PR if you find other missing core schema that is introduced in the future and we can review and merge it in.

**Comment by GordonSo** [comment]
The enhancement is now included in version 0.1.54

**Comment by GordonSo** [comment]
Since I cannot locate a json formatted meta schema for error, so I have to manually create one based on:
https://tools.ietf.org/html/draft-ietf-scim-api-08#section-3.10

This is what I came up with:
https://github.com/GordonSo/scimschema/pull/15/files#diff-ed08bcffeb63683c01ac702f4a7dfed6

The others were found from the rfc docs, so the latest version 0.1.55 will now contain 

1. urn:scim:api:messages:2.0:Error
2. urn:ietf:params:scim:schemas:core:2.0:ResourceType
3. urn:ietf:params:scim:schemas:core:2.0:Schema
4. urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig

 as a recognisable core schemas.

Thanks for reporting the problems to enrich this package.

**Comment by shubhamyedage** [comment]
@GordonSo Thanks,
Next time onwards will be raising issues instead of putting it in comments.
I will test this at earliest.
