### ISSUE TITLE
Missing new core schemas in updated version 0.1.55

### ISSUE THREAD

**Issue by shubhamyedage** [GordonSo/scimschema#16]
![image](https://user-images.githubusercontent.com/18259468/74646585-296f5200-51a0-11ea-9c41-bfb8c0dc8def.png)
Hi @GordonSo ,

Please check the schemas are not available when I update lib to 0.1.55.

**Comment by GordonSo** [comment]
I see, there is sometime out-of-date with the deploy script... looking into now

**Comment by GordonSo** [comment]
OK found the culprit, the manifest.in seems to be models for older version of the package ...

**Comment by GordonSo** [comment]
testing the newer script now

**Comment by GordonSo** [comment]
Fix with release 0.1.67
![image](https://user-images.githubusercontent.com/4214928/74693823-5f82f500-51e5-11ea-99d4-9d13a7b7ada8.png)

**Comment by shubhamyedage** [comment]
Thanks @GordonSo .
