### ISSUE TITLE
Test the core schema

### ISSUE THREAD

**Issue by poiuytrez** [GordonSo/scimschema#58]
I would like to the my json against the core user schema. How can I do that?

**Comment by mohankumaru** [comment]
There is an example provided in readme, did you try that?

**Comment by GordonSo** [comment]
Please see https://github.com/GordonSo/scimschema/blob/develop/README.rst
It has a link to a working example:
https://github.com/GordonSo/scimschema/blob/master/tests/test_scim_schema.py

If an extension schema is not needed "None" is acceptable e.g. 
```
from scimschema import validate

validate(data=content, extension_schema_definitions=None)
```
content being the 'json' you want to validate

nb: it always helps others to help you if a draft/attempted code snippet can be provided
