### ISSUE TITLE
Should correct "datetime" to "dateTime"

### ISSUE THREAD

**Issue by mohankumaru** [GordonSo/scimschema#68]
Hi @GordonSo ,

According to RFC7643, section7, the valid values for "type" are,  "string", "boolean", "decimal", "integer", "dateTime", "reference", and "complex".
But the module is expecting it to be "datetime".
The key in attribute_factory dictionary, we can change "datetime" to "dateTime".

Regards,
Mohan

**Comment by GordonSo** [comment]
Should now be addressed as per commit above
